name: .NET CI
on:
  push:
    branches:
      - master

jobs:
  build:
    name: CI Steps - .NET
    runs-on: windows-latest
    steps:
      - name: Get .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 6.0.x

      - name: Get JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
          
      #- name: Install SonarCloud scanner
      #  if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      #  shell: powershell
      #  run: |
      #    New-Item -Path .\.sonar\scanner -ItemType Directory
      #    dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      
      - name: Build
        run: dotnet build

      - name: Run tests and calculate code coverage
        run: dotnet test --collect:"XPlat Code Coverage" -- DataCollectorConfigurationFormat=JSON

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v2

      - name: Restore Packages, Build and Analyse Code

        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"${{ vars.SONAR_PROJECT }}" /o:"${{ vars.SONAR_ORGANIZATION }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ vars.SONAR_HOST_URL }}"
          dotnet restore
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
